name: Course Management Portal Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy the containers
        run: |
          cd /home/node3/course-portal/frontend/course_management_portal_frontend
          docker-compose stop course-frontend || true
          docker system prune -af || true
          docker-compose up -d course-frontend
          docker ps
